version: '2'

volumes:
  rust-www-src-sync:
    external: true
  nginx-sync:
    external: true

services:
  www:
    build:
      context: ./rust
      dockerfile: www.dockerfile
    volumes:
      - rust-www-src-sync:/var/www/src
    ports:
      - "3000:3000"
    networks:
      - backend

  nginx:
    build: nginx
    volumes: 
      - nginx-sync:/var/nginx
    networks:
      - frontend
      - backend   
    ports:
      - 80:80
      - 443:443
    links:
      - www:${WWW_DOMAIN}

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
