[package]
name = "www"
version = "0.1.0"
authors = ["Igarashi Syo <igara1119@gmail.com>"]

[dependencies]
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.8"
iron = "0.5.1"
router = "0.5.1"
mount = "0.3.0"
staticfile = "0.4.0"
