[package]
name = "www"
version = "0.1.0"
authors = ["Igarashi Syo <igara1119@gmail.com>"]

[dependencies.iron]
version = "0.6.0"

[dependencies.router]
version = "0.6.0"

[dependencies.mount]
version = "0.4.0"

[dependencies.staticfile]
version = "0.4.0"
