version: '2'

volumes:
  rust-www-src-sync:
    external: true
  nodejs-npm-sync:
    external: true
  python-sync:
    external: true

services:
  www:
    build:
      context: ./rust
      dockerfile: www.dockerfile
    volumes:
      - rust-www-src-sync:/rust/www/src
      - python-sync:/python
    ports:
      - 3000:3000
    networks:
      - backend
    environment:
      WWW_ENV: ${WWW_ENV}

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - www:www
    restart: always
    environment:
      DOMAINS: 'local.syonet.work -> http://www:3000'
      STAGE: '${WWW_ENV}'
      RESOLVER: '127.0.0.11 ipv6=off valid=60s'
      DYNAMIC_UPSTREAM: 'true'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: 0
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    networks:
      - frontend
      - backend

  npm:
    build:
      context: ./nodejs
      dockerfile: npm.dockerfile
    volumes:
      - nodejs-npm-sync:/nodejs
    volumes_from:
      - www

  parcel:
    build:
      context: ./nodejs
      dockerfile: parcel.dockerfile
    ports:
      - 1234:1234
    networks:
      - frontend
      - backend   
    volumes_from:
      - npm
      - www
    environment:
      WWW_ENV: ${WWW_ENV}

networks:
  frontend:
    driver: 'bridge'
  backend:
    driver: 'bridge'
