version: "2"

volumes:
  rust-www-src-sync:
    external: true
  nginx-sync:
    external: true
  nodejs-npm-sync:
    external: true

services:
  www:
    build:
      context: ./rust
      dockerfile: www.dockerfile
    volumes:
      - rust-www-src-sync:/rust/www/src
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      WWW_ENV: ${WWW_ENV}

  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - 80:80
      - 443:443
    links:
      - www
    restart: always
    environment:
      DOMAINS: "syonet.work -> http://www:3000"
      STAGE: ${WWW_ENV}
      DYNAMIC_UPSTREAM: "true"
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    networks:
      - frontend
      - backend
    extra_hosts:
      - "syonet.work:127.0.0.1"
      - "local.syonet.work:127.0.0.1"

  npm:
    build:
      context: ./nodejs
      dockerfile: npm.dockerfile
    volumes:
      - nodejs-npm-sync:/nodejs
    volumes_from:
      - www

  parcel:
    build:
      context: ./nodejs
      dockerfile: parcel.dockerfile
    ports:
      - 1234:1234
    networks:
      - frontend
      - backend   
    volumes_from:
      - npm
      - www
    environment:
      WWW_ENV: ${WWW_ENV}

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
